
adb start-server && adb shell pm uninstall --user 0 de.telekom.tsc
adb start-server && adb shell pm uninstall --user 0 com.google.android.cellbroadcastreceiver
adb start-server && adb shell pm uninstall --user 0 com.qualcomm.wfd.service
adb start-server && adb shell pm uninstall --user 0 com.qualcomm.qti.lpa
adb start-server && adb shell pm uninstall --user 0 com.miui.qr
adb start-server && adb shell pm uninstall --user 0 com.miui.analytics
adb start-server && adb shell pm uninstall --user 0 com.xiaomi.joyose
adb start-server && adb shell pm uninstall --user 0 com.qti.confuridialer
adb start-server && adb shell pm uninstall --user 0 com.google.android.syncadapters.contacts
adb start-server && adb shell pm uninstall --user 0 com.android.providers.contacts
adb start-server && adb shell pm uninstall --user 0 com.google.android.contacts
adb start-server && adb shell pm uninstall --user 0 com.miui.wmsvc
adb start-server && adb shell pm uninstall --user 0 com.amazon.appmanager
adb start-server && adb shell pm uninstall --user 0 com.tencent.soter.soterserver
adb start-server && adb shell pm uninstall --user 0 com.miui.hybrid.accessory
adb start-server && adb shell pm uninstall --user 0 com.miui.touchassistant
adb start-server && adb shell pm uninstall --user 0 com.miui.hybrid
adb start-server && adb shell pm uninstall --user 0 com.android.hotspot2.osulogin
adb start-server && adb shell pm uninstall --user 0 com.miui.player
adb start-server && adb shell pm uninstall --user 0 com.miui.msa.global
adb start-server && adb shell pm uninstall --user 0 com.miui.daemon
adb start-server && adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb start-server && adb shell pm uninstall --user 0 com.google.android.apps.maps
adb start-server && adb shell pm uninstall --user 0 com.xiaomi.glgm
adb start-server && adb shell pm uninstall --user 0 com.google.android.apps.wellbeing
adb start-server && adb shell pm uninstall --user 0 com.miui.micloudsync
adb start-server && adb shell pm uninstall --user 0 com.miui.videoplayer
adb start-server && adb shell pm uninstall --user 0 com.miui.mishare.connectivity
adb start-server && adb shell pm uninstall --user 0 com.mipay.wallet.in
adb start-server && adb shell pm uninstall --user 0 com.xiaomi.mi_connect_service
adb start-server && adb shell pm uninstall --user 0 com.xiaomi.payment
adb start-server && adb shell pm uninstall --user 0 com.google.android.apps.subscriptions.red
adb start-server && adb shell pm uninstall --user 0 com.xiaomi.mipicks
adb start-server && adb shell pm uninstall --user 0 com.miui.phrase
adb start-server && adb shell pm uninstall --user 0 com.miui.freeform
adb start-server && adb shell pm uninstall --user 0 com.facebook.services
adb start-server && adb shell pm uninstall --user 0 com.facebook.appmanager
adb start-server && adb shell pm uninstall --user 0 com.facebook.system
adb start-server && adb shell pm uninstall --user 0 com.android.providers.partnerbookmarks
adb start-server && adb shell pm uninstall --user 0 com.miui.cloudservice.sysbase
adb start-server && adb shell pm uninstall --user 0 com.miui.cloudbackup
adb start-server && adb shell pm uninstall --user 0 com.android.chrome
adb start-server && adb shell pm uninstall --user 0 com.google.android.calendar
adb start-server && adb shell pm uninstall --user 0 com.miui.backup
adb start-server && adb shell pm uninstall --user 0 com.google.android.apps.googleassistant
adb start-server && adb shell pm uninstall --user 0 com.miui.miwallpaper
adb start-server && adb shell pm uninstall --user 0 com.miui.cloudservice
adb start-server && adb shell pm uninstall --user 0 com.miui.yellowpage
adb start-server && adb shell pm uninstall --user 0 com.google.android.youtube
adb start-server && adb shell pm uninstall --user 0 com.miui.aod
adb start-server && adb shell pm uninstall --user 0 com.google.android.projection.gearhead
adb start-server && adb shell pm uninstall --user 0 com.google.android.setupwizard
adb start-server && adb shell pm uninstall --user 0 com.mi.globalminusscreen
adb start-server && adb shell pm uninstall --user 0 com.android.dreams.basic
adb start-server && adb shell pm uninstall --user 0 com.miui.extraphoto
adb start-server && adb shell pm uninstall --user 0 com.android.bookmarkprovider
adb start-server && adb shell pm uninstall --user 0 com.android.providers.calendar
adb start-server && adb shell pm uninstall --user 0 com.android.camera
adb start-server && adb shell pm uninstall --user 0 com.xiaomi.cameratools
adb start-server && adb shell pm uninstall --user 0 com.google.android.ims
adb start-server && adb shell pm uninstall --user 0 com.android.companiondevicemanager
adb start-server && adb shell pm uninstall --user 0 com.google.android.apps.restore
adb start-server && adb shell pm uninstall --user 0 com.google.android.apps.turbo
adb start-server && adb shell pm uninstall --user 0 com.miui.misound
adb start-server && adb shell pm uninstall --user 0 com.fido.asm
adb start-server && adb shell pm uninstall --user 0 com.fido.xiaomi.uafclient
adb start-server && adb shell pm uninstall --user 0 com.miui.gallery
adb start-server && adb shell pm uninstall --user 0 com.android.hotwordenrollment.xgoogle
adb start-server && adb shell pm uninstall --user 0 com.android.hotwordenrollment.okgoogle
adb start-server && adb shell pm uninstall --user 0 com.google.android.onetimeinitializer
adb start-server && adb shell pm uninstall --user 0 com.google.android.partnersetup
adb start-server && adb shell pm uninstall --user 0 com.mi.healthglobal
adb start-server && adb shell pm uninstall --user 0 com.android.wallpaper.livepicker
adb start-server && adb shell pm uninstall --user 0 com.qti.ltebc
adb start-server && adb shell pm uninstall --user 0 com.android.internal.systemui.onehanded.gestural
adb start-server && adb shell pm uninstall --user 0 org.codeaurora.ims
adb start-server && adb shell pm uninstall --user 0 com.android.dreams.phototable
adb start-server && adb shell pm uninstall --user 0 com.google.android.printservice.recommendation
adb start-server && adb shell pm uninstall --user 0 com.android.printspooler
adb start-server && adb shell pm uninstall --user 0 com.miui.audiomonitor
adb start-server && adb shell pm uninstall --user 0 com.qti.xdivert
adb start-server && adb shell pm uninstall --user 0 com.google.android.tts
adb start-server && adb shell pm uninstall --user 0 com.android.bips
adb start-server && adb shell pm uninstall --user 0 com.google.android.tag
adb start-server && adb shell pm uninstall --user 0 com.android.providers.userdictionary
adb start-server && adb shell pm uninstall --user 0 com.google.android.cellbroadcastservice
adb start-server && adb shell pm uninstall --user 0 com.android.cellbroadcastreceiver
adb start-server && adb shell pm uninstall --user 0 com.android.cellbroadcastreceiver.overlay.common
adb start-server && adb shell pm uninstall --user 0 com.google.android.cellbroadcastreceiver.overlay.miui
adb start-server && adb shell pm uninstall --user 0 com.google.android.cellbroadcastservice.overlay.miui
adb start-server && adb shell pm uninstall --user 0 com.android.cameraextensions
adb start-server && adb shell pm uninstall --user 0 com.android.inputdevices
adb start-server && adb shell pm uninstall --user 0 com.android.providers.media
adb start-server && adb shell pm uninstall --user 0 com.android.smspush
adb start-server && adb shell pm uninstall --user 0 com.miui.mediafeature
adb start-server && adb shell pm uninstall --user 0 com.android.mms.service
adb start-server && adb shell pm uninstall --user 0 com.milink.service
adb start-server && adb shell pm uninstall --user 0 com.google.android.ext.shared
adb start-server && adb shell pm uninstall --user 0 tv.chili.companion.android
adb start-server && adb shell pm uninstall --user 0 com.quicinc.voice.activation
adb start-server && adb shell pm uninstall --user 0 com.ironsource.appcloud.oobe.hutchison
adb start-server && adb shell pm uninstall --user 0 com.google.android.apps.setupwizard.searchselector
adb start-server && adb shell pm uninstall --user 0 com.aura.oobe.bouygues
adb start-server && adb shell pm uninstall --user 0 com.google.android.marvin.talkback
adb start-server && adb shell pm uninstall --user 0 com.miui.cotaservice
adb start-server && adb shell pm uninstall --user 0 com.xiaomi.miplay_client
adb start-server && adb shell pm uninstall --user 0 com.miui.powerkeeper
adb start-server && adb shell pm uninstall --user 0 com.google.android.dialer
