adb start-server && adb shell am force-stop com.android.bluetooth
adb start-server && adb shell am force-stop com.android.carrierdefaultapp
adb start-server && adb shell am force-stop com.miui.qr
adb start-server && adb shell am force-stop com.google.android.apps.docs
adb start-server && adb shell am force-stop com.miui.misound
adb start-server && adb shell am force-stop com.xiaomi.finddevice
adb start-server && adb shell am force-stop com.android.location.fused
adb start-server && adb shell am force-stop com.google.android.gm
adb start-server && adb shell am force-stop com.android.vending
adb start-server && adb shell am force-stop org.ifaa.aidl.manager
adb start-server && adb shell am force-stop com.android.inputdevices
adb start-server && adb shell am force-stop com.android.keychain
adb start-server && adb shell am force-stop com.qualcomm.location
adb start-server && adb shell am force-stop com.android.server.telecom
adb start-server && adb shell am force-stop org.mipay.android.manager
adb start-server && adb shell am force-stop com.xiaomi.bluetooth
adb start-server && adb shell am force-stop com.android.mms.service
adb start-server && adb shell am force-stop com.android.nfc
adb start-server && adb shell am force-stop com.google.android.dialer
adb start-server && adb shell am force-stop com.android.providers.telephony
adb start-server && adb shell am force-stop com.android.phone
adb start-server && adb shell am force-stop com.qualcomm.qti.poweroffalarm
adb start-server && adb shell am force-stop com.android.provision
adb start-server && adb shell am force-stop com.qti.snapdragon.qdcm_ff
adb start-server && adb shell am force-stop com.qualcomm.qti.ridemodeaudio
adb start-server && adb shell am force-stop com.miui.screenshot
adb start-server && adb shell am force-stop com.qualcomm.qti.seccamservice
adb start-server && adb shell am force-stop com.android.shell
adb start-server && adb shell am force-stop com.android.stk
adb start-server && adb shell am force-stop com.qualcomm.qti.simcontacts
adb start-server && adb shell am force-stop com.google.android.networkstack.tethering
adb start-server && adb shell am force-stop vendor.qti.imsrcs
adb start-server && adb shell am force-stop vendor.qti.iwlan
adb start-server && adb shell am force-stop com.qualcomm.wfd.service
adb start-server && adb shell am force-stop com.android.managedprovisioning
adb start-server && adb shell am force-stop com.qualcomm.qti.xrcb
adb start-server && adb shell am force-stop com.google.android.ext.shared
adb start-server && adb shell am force-stop com.google.android.webview
adb start-server && adb shell am force-stop com.android.bluetooth
adb start-server && adb shell am force-stop com.android.carrierdefaultapp
adb start-server && adb shell am force-stop com.android.backupconfirm
adb start-server && adb shell am force-stop com.android.carrierconfig
adb start-server && adb shell am force-stop com.android.cts.ctsshim
adb start-server && adb shell am force-stop com.android.cts.priv.ctsshim
adb start-server && adb shell am force-stop com.android.localtransport
adb start-server && adb shell am force-stop com.android.ons
adb start-server && adb shell am force-stop com.android.sharedstoragebackup
adb start-server && adb shell am force-stop com.android.wallpaperbackup
adb start-server && adb shell am force-stop com.android.wallpapercropper
adb start-server && adb shell am force-stop com.android.wifi.resources.xiaomi
adb start-server && adb shell am force-stop com.ifaa.seccam
adb start-server && adb shell am force-stop com.miui.core.internal.editor.services
adb start-server && adb shell am force-stop com.miui.core.internal.services
adb start-server && adb shell am force-stop com.miui.system
adb start-server && adb shell am force-stop com.miui.rom
adb start-server && adb shell am force-stop com.modemdebug
adb start-server && adb shell am force-stop com.qti.diagservices
adb start-server && adb shell am force-stop com.qti.dpmserviceapp
adb start-server && adb shell am force-stop com.qti.phone
adb start-server && adb shell am force-stop com.qti.qualcomm.datastatusnotification
adb start-server && adb shell am force-stop com.qualcomm.atfwd
adb start-server && adb shell am force-stop com.qualcomm.embms
adb start-server && adb shell am force-stop com.qualcomm.qcrilmsgtunnel
adb start-server && adb shell am force-stop com.qualcomm.qti.devicestatisticsservice
adb start-server && adb shell am force-stop com.qualcomm.qti.dynamicddsservice
adb start-server && adb shell am force-stop com.qualcomm.qti.ims
adb start-server && adb shell am force-stop com.qualcomm.qti.lpa
adb start-server && adb shell am force-stop com.qualcomm.qti.remoteSimlockAuth
adb start-server && adb shell am force-stop com.qualcomm.qti.telephonyservice
adb start-server && adb shell am force-stop com.qualcomm.qti.uim
adb start-server && adb shell am force-stop com.qualcomm.qti.uimGbaApp
adb start-server && adb shell am force-stop com.qualcomm.qti.workloadclassifier
adb start-server && adb shell am force-stop com.qualcomm.timeservice
adb start-server && adb shell am force-stop com.qualcomm.uimremoteclient
adb start-server && adb shell am force-stop com.qualcomm.uimremoteserver
adb start-server && adb shell am force-stop com.xiaomi.micloud.sdk
adb start-server && adb shell am force-stop com.qti.confuridialer
adb start-server && adb shell am force-stop com.goodix.gftest
adb start-server && adb shell am force-stop com.android.mms.service
adb start-server && adb shell am force-stop com.android.internal.systemui.onehanded.gestural
adb start-server && adb shell am force-stop com.android.internal.display.cutout.emulation.hole
adb start-server && adb shell am force-stop com.qti.snapdragon.qdcm_ff
adb start-server && adb shell am force-stop com.qualcomm.qti.ridemodeaudio
adb start-server && adb shell am force-stop com.miui.screenshot
adb start-server && adb shell am force-stop com.qualcomm.qti.seccamservice
adb start-server && adb shell am force-stop com.fingerprints.sensortesttool
adb start-server && adb shell am force-stop com.android.shell
adb start-server && adb shell am force-stop com.android.stk
adb start-server && adb shell am force-stop com.qualcomm.qti.simcontacts
adb start-server && adb shell am force-stop com.google.android.connectivity.resources
adb start-server && adb shell am force-stop com.android.internal.display.cutout.emulation.tall
adb start-server && adb shell am force-stop com.google.android.networkstack.tethering
adb start-server && adb shell am force-stop vendor.qti.imsrcs
adb start-server && adb shell am force-stop vendor.qti.iwlan
adb start-server && adb shell am force-stop com.android.vpndialogs
adb start-server && adb shell am force-stop com.android.internal.display.cutout.emulation.waterfall
adb start-server && adb shell am force-stop com.qualcomm.wfd.service
adb start-server && adb shell am force-stop com.android.managedprovisioning
adb start-server && adb shell am force-stop com.qualcomm.qti.xrcb
adb start-server && adb shell am force-stop com.xiaomi.bluetooth
adb start-server && adb shell am force-stop com.android.bluetooth
adb start-server && adb shell am force-stop com.apkpure.aegon
adb start-server && adb shell am force-stop com.apkupdater
adb start-server && adb shell am force-stop com.applisto.appcloneR
adb start-server && adb shell am force-stop com.mi.globalminusscreen
adb start-server && adb shell am force-stop cm.aptoide.pt
adb start-server && adb shell am force-stop com.google.android.apps.authenticator2
adb start-server && adb shell am force-stop com.handycloset.android.eraser
adb start-server && adb shell am force-stop com.binance.dev
adb start-server && adb shell am force-stop com.brave.browser
adb start-server && adb shell am force-stop com.canva.editor
adb start-server && adb shell am force-stop com.rhmsoft.code
adb start-server && adb shell am force-stop com.google.android.gm
adb start-server && adb shell am force-stop com.hittechsexpertlimited.hitbtc
adb start-server && adb shell am force-stop com.imaginbank.app
adb start-server && adb shell am force-stop com.kiwibrowser.browser
adb start-server && adb shell am force-stop com.kiwibrowser.browses
adb start-server && adb shell am force-stop com.mobile.legends
adb start-server && adb shell am force-stop com.paperwallet.top
adb start-server && adb shell am force-stop com.paypal.android.p2pmobile
adb start-server && adb shell am force-stop com.paypal.merchant.client
adb start-server && adb shell am force-stop com.google.android.dialer
adb start-server && adb shell am force-stop com.android.phone
adb start-server && adb shell am force-stop com.google.android.apps.photos
adb start-server && adb shell am force-stop com.soundcloud.android
adb start-server && adb shell am force-stop com.stormgain.mobile
adb start-server && adb shell am force-stop com.panzerdog.tacticool
adb start-server && adb shell am force-stop ir.ilmili.telegraph
adb start-server && adb shell am force-stop com.android.thememanager
adb start-server && adb shell am force-stop com.uphold.wallet
adb start-server && adb shell am force-stop com.whatsapp
adb start-server && adb shell am force-stop io.getwombat.android
adb start-server && adb shell am force-stop com.coinbase.android
adb start-server && adb shell am force-stop com.google.android.contacts
adb start-server && adb shell am force-stop com.google.android.cellbroadcastreceiver
